# Generated by Django 4.2.2 on 2023-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=256)),
                ("message", models.TextField(default="")),
                ("send_date", models.DateTimeField(verbose_name="send on date...")),
                ("email_to", models.EmailField(default="", max_length=254)),
            ],
        ),
    ]
