# Generated by Django 4.2.2 on 2023-09-09 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tap",
            name="added_on",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="tap",
            name="email_to",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
