# Generated by Django 4.2.2 on 2023-09-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0002_tap_added_on_alter_tap_email_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        max_length=1,
                    ),
                ),
                ("date", models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="tap",
            name="send_days",
            field=models.ManyToManyField(to="tapa.day"),
        ),
    ]
