# Generated by Django 4.2.2 on 2023-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0004_rename_date_day_time_alter_tap_send_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="day",
            field=models.CharField(
                choices=[
                    ("0", "Monday"),
                    ("1", "Tuesday"),
                    ("2", "Wednesday"),
                    ("3", "Thursday"),
                    ("4", "Friday"),
                    ("5", "Saturday"),
                    ("6", "Sunday"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="time",
            field=models.TimeField(blank=True),
        ),
    ]
