# Generated by Django 4.2.2 on 2023-09-09 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0006_tap_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tap",
            name="send_days",
        ),
        migrations.AddField(
            model_name="day",
            name="tap",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to="tapa.tap"
            ),
            preserve_default=False,
        ),
    ]
