# Generated by Django 4.2.2 on 2023-09-10 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0007_remove_tap_send_days_day_tap"),
    ]

    operations = [
        migrations.AddField(
            model_name="tap",
            name="send_time",
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
