# Generated by Django 4.2.2 on 2023-09-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0008_tap_send_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tap",
            name="send_time",
        ),
    ]
