# Generated by Django 4.2.2 on 2023-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0009_remove_tap_send_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tap",
            name="send_date",
            field=models.DateTimeField(blank=True, verbose_name="send on date..."),
        ),
    ]
