# Generated by Django 4.2.2 on 2023-09-10 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0010_alter_tap_send_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tap",
            name="send_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="send on date...",
            ),
        ),
    ]
