# Generated by Django 4.2.2 on 2023-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0011_alter_tap_send_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tap",
            name="send_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="send on date..."
            ),
        ),
    ]
