# Generated by Django 4.2.2 on 2023-09-22 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tapa", "0014_alter_day_tap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tap",
            name="added_on",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
